name: Clojure CI

on:
  push:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Prepare java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Setup Clojure
      # You may pin to the exact commit or the version.
      # uses: DeLaGuardo/setup-clojure@5042876523f30f5efcf1d6feaa48bd1498d7814f
      uses: DeLaGuardo/setup-clojure@3.5
      with:
        # Clojure CLI version to make available on the path.
        cli: 1.10.3.1058
    - uses: actions/checkout@v2
    - name: Install dependencies
      working-directory: ./server
      run: clojure -P
    - name: Prep library
      working-directory: ./server
      run: clojure -T:build compile
    - name: Build static
      working-directory: ./server
      run: clojure -M:build-static
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: docs # The folder the action should deploy.
